version: "3.3"
services:
  netboot-tftp:
    image: dgpublicimagesprod.azurecr.io/planetexpress/netboot-tftp:latest
    pull_policy: always
    container_name: netboot-tftp
    volumes:
      - $HOME/netboot/config/menus:/srv/tftp/ipxe
    ports:
      - 69:69/udp #TFTP
    restart: unless-stopped

  netboot-http:
    image: dgpublicimagesprod.azurecr.io/planetexpress/netboot-http:latest
    pull_policy: always
    container_name: netboot-http
    # This corresponds to the `master` user on the netboot server
    user: 1000:1000
    volumes:
      - $HOME/netboot/assets:/assets
    ports:
      - 80:80 #Assets
    restart: unless-stopped

  netboot-cleaner:
    image: dgpublicimagesprod.azurecr.io/planetexpress/netboot-cleaner:latest
    container_name: netboot-cleaner
    # This corresponds to the `master` user on the netboot server
    user: 1000:1000
    env_file:
      - $HOME/cleaner.env
    volumes:
      - $HOME/netboot/assets:/cleaning
    restart: unless-stopped

  netboot-sync:
    image: dgpublicimagesprod.azurecr.io/planetexpress/netboot-sync:latest
    pull_policy: always
    container_name: netboot-sync
    user: 1000:1000
    env_file:
      - $HOME/sync.env
    volumes:
      - $HOME/netboot/assets:/home/syncer/
    restart: unless-stopped

  netboot-monitoring:
    image: dgpublicimagesprod.azurecr.io/planetexpress/netboot-monitoring:latest
    container_name: netboot-monitoring
    env_file:
      - $HOME/monitoring.env

    restart: unless-stopped
    
  netboot-build-main-ipxe-menus:
    image: dgpublicimagesprod.azurecr.io/planetexpress/netboot-ipxe-menu-generator:latest
    pull_policy: always
    container_name: netboot-build-main-ipxe-menus
    env_file:
      - $HOME/ipxe-menu-generator.env
    volumes:
      - $HOME/netboot/assets:/assets
      - $HOME/netboot/config/menus:/menus
    restart:
      unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 netboot-build-main-ipxe-menus netboot-http netboot-tftp netboot-sync netboot-monitoring netboot-cleaner
