name: Docker build and push
run-name: Docker build and push

on:
  workflow_call:
    inputs:
      docker_image_tag:
        description: "image tag to use for the docker image"
        required: true
        type: string
      docker_bakefile_path:
        description: "Path to the docker bake file"
        required: false
        type: string
      azure_managed_identity_clientid:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.repository }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Bake
        uses: ./.github/actions/docker-bake
        with:
            docker_image_tag: ${{ inputs.docker_image_tag }}
            docker_bakefile_path: ${{ inputs.docker_bakefile_path }}
            azure_managed_identity_clientid: ${{ inputs.azure_managed_identity_clientid }}
